/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Form_Utama extends javax.swing.JFrame {
   
    /**
     * Creates new form Form_Utama
     */
    
    public void tampilTable(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("Nama Barang");
        tabel.addColumn("Harga Satuan");
        tabel.addColumn("Jumlah Beli");
        tabel.addColumn("Total");
        
        tblKeranjang.setModel(tabel);
                
    }
    
    public void hitungTotalHarga(){
        DefaultTableModel model = (DefaultTableModel) tblKeranjang.getModel();
        int totalHarga = 0;
            
        for(int j = 0; j < tblKeranjang.getRowCount(); j++){
            totalHarga = totalHarga + Integer.parseInt(model.getValueAt(j, 3).toString());     
        }

        txtJmlHarga.setText(String.valueOf(totalHarga));
    }
    
    public Form_Utama() {
        initComponents();
        tampilTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbNmBarang = new javax.swing.JComboBox<>();
        txtHarga = new javax.swing.JTextField();
        txtJmlBeli = new javax.swing.JTextField();
        txtJmlHarga = new javax.swing.JTextField();
        txtJmlKembalian = new javax.swing.JTextField();
        btnHapusItem = new javax.swing.JButton();
        btnHitungJmlKembalian = new javax.swing.JButton();
        txtJmlBayar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKeranjang = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnHitungJmlHarga1 = new javax.swing.JButton();
        btnEditItem = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Kasir Sederhana");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel1.setText("APLIKASI KASIR FAMUWA COMPUTER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama Barang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 112, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Harga Barang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 155, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Jumlah Harga");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 239, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Jumlah Beli");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 197, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jumlah Kembalian");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 323, -1, -1));

        cbNmBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbNmBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Barang --", "Laptop ASUS ROG", "Mouse Logitec", "Keyboard" }));
        cbNmBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNmBarangActionPerformed(evt);
            }
        });
        getContentPane().add(cbNmBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 109, -1, -1));

        txtHarga.setEditable(false);
        txtHarga.setBackground(new java.awt.Color(102, 255, 255));
        txtHarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHarga.setText("0");
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 152, 140, -1));

        txtJmlBeli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtJmlBeli.setText("0");
        txtJmlBeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJmlBeliKeyReleased(evt);
            }
        });
        getContentPane().add(txtJmlBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 194, 140, -1));

        txtJmlHarga.setEditable(false);
        txtJmlHarga.setBackground(new java.awt.Color(102, 255, 255));
        txtJmlHarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtJmlHarga.setText("0");
        getContentPane().add(txtJmlHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 236, 140, -1));

        txtJmlKembalian.setEditable(false);
        txtJmlKembalian.setBackground(new java.awt.Color(102, 255, 255));
        txtJmlKembalian.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtJmlKembalian.setText("0");
        getContentPane().add(txtJmlKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 320, 140, -1));

        btnHapusItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHapusItem.setText("Hapus Item");
        btnHapusItem.setEnabled(false);
        btnHapusItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusItemActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapusItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 110, -1));

        btnHitungJmlKembalian.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHitungJmlKembalian.setText("Hitung Jumlah Kembalian");
        btnHitungJmlKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungJmlKembalianActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitungJmlKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 319, -1, -1));

        txtJmlBayar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtJmlBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJmlBayarKeyReleased(evt);
            }
        });
        getContentPane().add(txtJmlBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 278, 140, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Jumlah Bayar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 281, -1, -1));

        btnBatal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBatal.setText("Batalkan Transaksi");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 150, -1));

        btnKeluar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 100, -1));

        btnCetak.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCetak.setText("Cetak Struk");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        tblKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKeranjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKeranjangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKeranjang);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 550, 250));

        btnTambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTambah.setText("Tambah Ke Keranjang");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 195, 190, -1));

        btnHitungJmlHarga1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHitungJmlHarga1.setText("Hitung Jumlah Harga");
        btnHitungJmlHarga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungJmlHarga1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitungJmlHarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 235, 185, -1));

        btnEditItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEditItem.setText("Edit Item");
        btnEditItem.setEnabled(false);
        btnEditItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditItemActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 110, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbNmBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNmBarangActionPerformed
        
        switch(cbNmBarang.getSelectedIndex()){
            case 0:
            {
              txtHarga.setText(String.valueOf("0"));
            }
            break;
            
            case 1:
            {
              txtHarga.setText(String.valueOf("20000000"));
            }
            break;
            
            case 2:
            {
              txtHarga.setText(String.valueOf("100000"));
            }
            break;
            
            case 3:
            {
              txtHarga.setText(String.valueOf("230000"));
            }
            break;
        }
        
        if(cbNmBarang.getSelectedIndex() == 0){  
            txtJmlBeli.setText("");
        } else {
            txtJmlBeli.setText("1");
        }
        
    }//GEN-LAST:event_cbNmBarangActionPerformed

    private void txtJmlBeliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJmlBeliKeyReleased
        // TODO add your handling code here:
//        if(txtJmlBeli.getText().equals("") || txtJmlBeli.getText().equals("0")){
//           JOptionPane.showMessageDialog(rootPane, "Jumlah Beli Tidak Boleh Kosong!!!"); 
//           txtJmlBeli.setText("1");
//        }else {
//            int jumlahBeli = Integer.parseInt(txtJmlBeli.getText());
//            int harga = Integer.parseInt(txtHarga.getText());
//            int jumlahHarga = harga * jumlahBeli;
//            txtJmlHarga.setText(String.valueOf(jumlahHarga));
//        }
        
    }//GEN-LAST:event_txtJmlBeliKeyReleased

    private void txtJmlBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJmlBayarKeyReleased
        
        if(txtJmlBayar.getText().equals("") || txtJmlBayar.getText().equals("0")){
           JOptionPane.showMessageDialog(rootPane, "Jumlah Bayar Tidak Boleh Kosong!!!"); 
        } else {
            int jharga,bayar,hasil;
        
            jharga=Integer.parseInt(txtJmlHarga.getText());
            bayar=Integer.parseInt(txtJmlBayar.getText());
            hasil= bayar-jharga;
            txtJmlKembalian.setText(String.valueOf(hasil));
        }
    }//GEN-LAST:event_txtJmlBayarKeyReleased

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        cbNmBarang.setSelectedIndex(0);
        txtHarga.setText("0");
        txtJmlBeli.setText("0");
        txtJmlHarga.setText("0");
        txtJmlBayar.setText("");
        txtJmlKembalian.setText("0");
        
        DefaultTableModel model = (DefaultTableModel) tblKeranjang.getModel();
        for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }
        
        btnEditItem.setEnabled(false);
        btnHapusItem.setEnabled(false);
        btnTambah.setEnabled(true);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnHapusItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusItemActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblKeranjang.getModel();
        
        try{
            int SelectedRowIndex = tblKeranjang.getSelectedRow();
            
            int jmlHarga = Integer.parseInt(tblKeranjang.getValueAt(SelectedRowIndex, 3).toString());
            
            model.removeRow(SelectedRowIndex);
            
            hitungTotalHarga();
                    
            txtHarga.setText("");
            txtJmlBeli.setText("");
            cbNmBarang.setSelectedIndex(0);
            
            btnEditItem.setEnabled(false);
            btnHapusItem.setEnabled(false);
            btnTambah.setEnabled(true);

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnHapusItemActionPerformed

    private void btnHitungJmlKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungJmlKembalianActionPerformed
        Double jharga,bayar,hasil;
        
        jharga=Double.parseDouble(txtJmlHarga.getText());
        bayar=Double.parseDouble(txtJmlBayar.getText());
        hasil=bayar-jharga;
        txtJmlKembalian.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnHitungJmlKembalianActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed

        if(txtJmlBayar.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Lakukan Proses Pembayaran Terlebih Dahulu!!!");
        } else {
            try{
                DefaultTableModel model = (DefaultTableModel) tblKeranjang.getModel();
                String totalHarga = txtJmlHarga.getText();
                String tunai = txtJmlBayar.getText();
                String kembalian = txtJmlKembalian.getText();
                String[] judul = {"Nama Barang", "Harga", "Jumlah", "Total"};
                String[][] isi = new String[tblKeranjang.getRowCount()][tblKeranjang.getColumnCount()];

                for(int i = 0; i < tblKeranjang.getRowCount(); i++){
                    for(int j = 0; j < tblKeranjang.getColumnCount(); j++){
                        isi[i][j] = model.getValueAt(i, j).toString();
                    }
                }

                Cetak tabel = new Cetak(judul, isi, tblKeranjang.getRowCount(), tblKeranjang.getColumnCount(), totalHarga, tunai, kembalian);

                JOptionPane.showMessageDialog(rootPane, "Transaksi Selesai!!..");

                cbNmBarang.setSelectedIndex(0);
                txtHarga.setText("0");
                txtJmlBeli.setText("0");
                txtJmlHarga.setText("0");
                txtJmlBayar.setText("");
                txtJmlKembalian.setText("0");

                for(int l = model.getRowCount() - 1; l >= 0; l-- ) {
                    model.removeRow(l);
                }

                btnEditItem.setEnabled(false);
                btnHapusItem.setEnabled(false);
                btnTambah.setEnabled(true);
            
            }catch(Exception e){
                System.out.println(e);
            } 
        }
        
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        
        if(cbNmBarang.getSelectedItem().equals("-- Pilih Barang --")){
            JOptionPane.showMessageDialog(rootPane, "Pilih Barang terlebih dahulu!!!");
        } else {
            DefaultTableModel model = (DefaultTableModel) tblKeranjang.getModel();
            int jmlHargaBarang = Integer.parseInt(txtHarga.getText()) * Integer.parseInt(txtJmlBeli.getText());
            model.addRow(new Object[] {cbNmBarang.getSelectedItem(), txtHarga.getText(), txtJmlBeli.getText(), jmlHargaBarang});

            hitungTotalHarga();

            txtHarga.setText("");
            txtJmlBeli.setText("");
            cbNmBarang.setSelectedIndex(0);
        }
        
        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tblKeranjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKeranjangMouseClicked
        int table = tblKeranjang.getSelectedRow();
        
        String a = tblKeranjang.getValueAt(table, 0).toString();
        String b = tblKeranjang.getValueAt(table, 1).toString();
        String c = tblKeranjang.getValueAt(table, 2).toString();
        
        cbNmBarang.setSelectedItem(a);
        txtHarga.setText(b);
        txtJmlBeli.setText(c);
        
        btnEditItem.setEnabled(true);
        btnHapusItem.setEnabled(true);
        btnTambah.setEnabled(false);
    }//GEN-LAST:event_tblKeranjangMouseClicked

    private void btnHitungJmlHarga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungJmlHarga1ActionPerformed
        Double harga,jbeli,hasil;
        harga=Double.parseDouble(txtHarga.getText());
        jbeli=Double.parseDouble(txtJmlBeli.getText());
        hasil=harga*jbeli;
        txtJmlHarga.setText(String.valueOf(hasil));      
    }//GEN-LAST:event_btnHitungJmlHarga1ActionPerformed

    private void btnEditItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditItemActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblKeranjang.getModel();
        int i = tblKeranjang.getSelectedRow();
                
        if(i >= 0) 
        {
            model.setValueAt(cbNmBarang.getSelectedItem(), i, 0);
            model.setValueAt(txtHarga.getText(), i, 1);
            model.setValueAt(txtJmlBeli.getText(), i, 2);
           
            int jmlHargaBarang = Integer.parseInt(txtHarga.getText()) * Integer.parseInt(txtJmlBeli.getText());
    
            model.setValueAt(jmlHargaBarang, i, 3);
            hitungTotalHarga();
            
            txtHarga.setText("");
            txtJmlBeli.setText("");
            cbNmBarang.setSelectedIndex(0);
            
            btnEditItem.setEnabled(false);
            btnHapusItem.setEnabled(false);
            btnTambah.setEnabled(true);
            
        }
        else{
            System.out.println("Update Error");
        }
    }//GEN-LAST:event_btnEditItemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cbNmBarang.setSelectedIndex(0);
        txtHarga.setText("");
        txtJmlBeli.setText("");
        
        btnEditItem.setEnabled(false);
        btnHapusItem.setEnabled(false);
        btnTambah.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnEditItem;
    private javax.swing.JButton btnHapusItem;
    private javax.swing.JButton btnHitungJmlHarga1;
    private javax.swing.JButton btnHitungJmlKembalian;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbNmBarang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblKeranjang;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJmlBayar;
    private javax.swing.JTextField txtJmlBeli;
    private javax.swing.JTextField txtJmlHarga;
    private javax.swing.JTextField txtJmlKembalian;
    // End of variables declaration//GEN-END:variables
}
